# Generated by Django 4.2.4 on 2025-06-13 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def remove_invalid_chats(apps, schema_editor):
    Chat = apps.get_model('api', 'Chat')
    # Remove all existing chats since they have invalid user references
    Chat.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_invalid_chats),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='accounts.customusermodel'),
        ),
    ]
