# Generated by Django 4.2.4 on 2025-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_leader_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF documents related to this leader', null=True, upload_to='leader_pdfs/'),
        ),
        migrations.AddField(
            model_name='leader',
            name='pkl_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
