# Generated by Django 4.2.4 on 2025-06-13 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_alter_chat_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="formatted_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.leader"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
