# Generated by Django 4.2.4 on 2025-06-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_chat_formatted_response_chat_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="formatted_response",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="metadata",
        ),
        migrations.AlterField(
            model_name="chat",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="api.leader",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
