# Generated by Django 4.2.4 on 2025-06-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leader_pdf_file_leader_pkl_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=100)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.leader')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
