# Generated by Django 4.2.4 on 2025-07-27 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_chat_formatted_response_remove_chat_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
