# Generated by Django 4.2.4 on 2025-03-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
